// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5nKSirXODH8CXufha7sg9NV1J0du9rRk',
    appId: '1:244567319909:web:7a8d115f08a75600bb2d8c',
    messagingSenderId: '244567319909',
    projectId: 'slay-the-spire-wiki-e9f46',
    authDomain: 'slay-the-spire-wiki-e9f46.firebaseapp.com',
    storageBucket: 'slay-the-spire-wiki-e9f46.firebasestorage.app',
    measurementId: 'G-GPRVNBT604',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5GKLzzDLtw6znNYEO6zotPg68CPrOQ6o',
    appId: '1:244567319909:android:cdb88f6e6cae7478bb2d8c',
    messagingSenderId: '244567319909',
    projectId: 'slay-the-spire-wiki-e9f46',
    storageBucket: 'slay-the-spire-wiki-e9f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpYG86gR92Y0ogFcv2VOSu3IVx6K9_dQ',
    appId: '1:244567319909:ios:f1f85163be4be6bdbb2d8c',
    messagingSenderId: '244567319909',
    projectId: 'slay-the-spire-wiki-e9f46',
    storageBucket: 'slay-the-spire-wiki-e9f46.firebasestorage.app',
    iosBundleId: 'com.megatown.spireWiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpYG86gR92Y0ogFcv2VOSu3IVx6K9_dQ',
    appId: '1:244567319909:ios:f1f85163be4be6bdbb2d8c',
    messagingSenderId: '244567319909',
    projectId: 'slay-the-spire-wiki-e9f46',
    storageBucket: 'slay-the-spire-wiki-e9f46.firebasestorage.app',
    iosBundleId: 'com.megatown.spireWiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5nKSirXODH8CXufha7sg9NV1J0du9rRk',
    appId: '1:244567319909:web:74788c13efe17604bb2d8c',
    messagingSenderId: '244567319909',
    projectId: 'slay-the-spire-wiki-e9f46',
    authDomain: 'slay-the-spire-wiki-e9f46.firebaseapp.com',
    storageBucket: 'slay-the-spire-wiki-e9f46.firebasestorage.app',
    measurementId: 'G-G8PDDZE4F9',
  );

}